name = "libmad"
version = "0.15.1b"
source = "https://downloads.sourceforge.net/mad/libmad-0.15.1b.tar.gz"
deps = [
    "base-dev 3.0"
]
extras = [
    "https://www.linuxfromscratch.org/patches/blfs/13.0/libmad-0.15.1b-fixes-1.patch"
]