name = "libqmi"
version = "1.38.0"
source = "https://gitlab.freedesktop.org/mobile-broadband/libqmi/-/archive/1.38.0/libqmi-1.38.0.tar.gz"
deps = [
    "libmbim 1.34.0",
    "libgudev 238"
]
extras = [
    
]