name = "itstool"
version = "2.0.7"
source = "https://github.com/itstool/itstool/archive/2.0.7/itstool-2.0.7.tar.gz"
deps = [
    "docbook-xml 4.5",
    "lxml 6.0.2"
]
extras = [
    "https://www.linuxfromscratch.org/patches/blfs/13.0/itstool-2.0.7-lxml-1.patch"
]