name = "colord"
version = "1.4.8"
source = "https://www.freedesktop.org/software/colord/releases/colord-1.4.8.tar.xz"
deps = [
    "lcms 2.18",
    "libgudev 238",
    "libgusb 0.4.9",
    "polkit 127",
    "vala 0.56.18"
]
extras = [
    
]