name = "nvidia-egl"
version = "3.0"
source = "none"
deps = [
    "libgbm 1.0.4",
    "libglvnd 1.7.0",
    "wayland-protocols 1.47",
    "xorg-libs 3.0",
    "hwdata 0.404"
]
extras = [
    
]
runtime_deps = [
    "wayland-protocols 1.47",
    "pciutils 3.14.0",
    "hwdata 0.404",
    "dri 25.3.5"
]
