name = "gtk4"
version = "4.20.3"
source = "https://download.gnome.org/sources/gtk/4.20/gtk-4.20.3.tar.xz"
deps = [
    "gdk-pixbuf 2.44.5",
    "graphene 1.10.8",
    "iso-codes 4.20.1",
    "libepoxy 1.5.10",
    "librsvg 2.61.4",
    "libxkbcommon 1.13.1",
    "pango 1.57.0",
    "pygobject 3.54.5",
    "gst-plugins-bad 1.28.0",
    "glslc 2026.1",
    "hicolor-icon-theme 0.18"
]
extras = [
    
]