name = "adwaita-icon-theme"
version = "49.0"
source = "https://download.gnome.org/sources/adwaita-icon-theme/49/adwaita-icon-theme-49.0.tar.xz"
deps = [
    "gtk3 3.24.51",
    "gtk4 4.20.3",
    "librsvg 2.61.4"
]
extras = [
    
]