name = "librsvg"
version = "2.61.4"
source = "https://download.gnome.org/sources/librsvg/2.61/librsvg-2.61.4.tar.xz"
deps = [
    "cairo 1.18.4",
    "cargo-c 0.10.20",
    "pango 1.57.0",
    "gdk-pixbuf 2.44.5",
    "vala 0.56.18"
]
extras = [
    
]