name = "intltool"
version = "0.51.0"
source = "https://launchpad.net/intltool/trunk/0.51.0/+download/intltool-0.51.0.tar.gz"
deps = [
    "xml-parser 2.47"
]
extras = [
    
]
runtime_deps = [
    "autoconf 2.72",
    "automake 1.18.1",
    "bash 5.3",
    "glibc 2.43",
    "grep 3.12",
    "perl mime-base32-1.303",
    "sed 4.9"
]
