name = "libxfce4util"
version = "4.20.1"
source = "https://archive.xfce.org/src/xfce/libxfce4util/4.20/libxfce4util-4.20.1.tar.bz2"
deps = [
    "base-xorg 3.0",
    "vala 0.56.18"
]
extras = [
    
]