name = "shadow"
version = "4.19.3"
source = "https://github.com/shadow-maint/shadow/releases/download/4.19.3/shadow-4.19.3.tar.xz"
deps = [
    "libxcrypt 4.5.2"
]
extras = [
    
]
runtime_deps = [
    "glibc 2.43",
    "libxcrypt 4.5.2",
    "acl 2.3.2"
]