name = "file"
version = "5.46"
source = "https://astron.com/pub/file/file-5.46.tar.gz"
deps = [
    "zstd 1.5.7"
]
extras = [
    
]
runtime_deps = [
    "glibc 2.43",
    "zlib 1.3.2",
    "bzip2 1.0.8",
    "xz 5.8.2",
]