name = "konsole"
version = "25.08.3"
source = "https://download.kde.org/stable/release-service/25.08.3/src/konsole-25.08.3.tar.xz"
deps = [
    "kde-framework 6.23.0"
]
extras = [
    "https://www.linuxfromscratch.org/patches/blfs/svn/konsole-adjust_scrollbar-1.patch"
]