name = "base-kde"
version = "3.0"
source = "none"
deps = [
    "ark 25.08.3",
    "dolphin-plugins 25.08.3",
    "kdenlive 25.08.3",
    "kmix 25.08.3",
    "khelpcenter 25.08.3",
    "konsole 25.08.3",
    "kio-extras 25.08.3",
    "gwenview 25.08.3",
    "kirigami-addons 1.10.0",
    "pulseaudio-qt 1.7.0",
    "kde-plasma 6.6.1",
    "firefox 140.8.0",
    "plasma-login-manager 6.6.1"
]
extras = [
    
]