set -e

echo "Installing in ${LFS:?}"

. utils.sh
. packages.sh

build_package "manpages" "https://www.kernel.org/pub/linux/docs/man-pages/man-pages-6.18.tar.xz"
build_package "ianaetc" "https://github.com/Mic92/iana-etc/releases/download/20260805/iana-etc-20260805.tar.gz"
build_package "glibc" "https://ftpmirror.gnu.org/glibc/glibc-2.44.tar.xz" "https://www.linuxfromscratch.org/patches/downloads/glibc/glibc-fhs-1.patch" "https://www.linuxfromscratch.org/patches/downloads/glibc/glibc-2.44-upstream_fixes-1.patch"
build_package "zlib" "https://zlib.net/fossils/zlib-1.3.2.tar.gz"
build_package "bzip2" "https://www.sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz" "https://www.linuxfromscratch.org/patches/downloads/bzip2/bzip2-1.0.8-install_docs-1.patch"
build_package "xz" "https://github.com//tukaani-project/xz/releases/download/v5.8.3/xz-5.8.3.tar.xz"
build_package "lz4" "https://github.com/lz4/lz4/releases/download/v1.10.0/lz4-1.10.0.tar.gz"
build_package "zstd" "https://github.com/facebook/zstd/releases/download/v1.5.7/zstd-1.5.7.tar.gz"
build_package "file" "https://astron.com/pub/file/file-5.48.tar.gz"
build_package "readline" "https://ftpmirror.gnu.org/readline/readline-8.3.tar.gz"
build_package "pcre2" "https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10.47/pcre2-10.47.tar.bz2"
build_package "m4" "https://ftpmirror.gnu.org/m4/m4-1.4.21.tar.xz"
build_package "bc" "https://github.com/gavinhoward/bc/releases/download/7.0.3/bc-7.0.3.tar.xz"
build_package "flex" "https://github.com/westes/flex/releases/download/v2.6.4/flex-2.6.4.tar.gz"
build_package "tcl" "https://downloads.sourceforge.net/tcl/tcl8.6.18-src.tar.gz" "https://downloads.sourceforge.net/tcl/tcl8.6.18-html.tar.gz"
build_package "expect" "https://prdownloads.sourceforge.net/expect/expect5.45.4.tar.gz" "https://www.linuxfromscratch.org/patches/downloads/expect/expect-5.45.4-gcc15-1.patch"
build_package "dejagnu" "https://ftpmirror.gnu.org/dejagnu/dejagnu-1.6.3.tar.gz"
build_package "ninja" "https://github.com/ninja-build/ninja/archive/v1.13.2/ninja-1.13.2.tar.gz"
build_package "pkgconf" "https://distfiles.ariadne.space/pkgconf/pkgconf-3.0.5.tar.xz"
build_package "binutils" "https://sourceware.org/pub/binutils/releases/binutils-2.47.tar.xz"
build_package "gmp" "https://ftpmirror.gnu.org/gmp/gmp-6.3.0.tar.xz"
build_package "mpfr" "https://ftpmirror.gnu.org/mpfr/mpfr-4.2.2.tar.xz"
build_package "mpc" "https://ftpmirror.gnu.org/mpc/mpc-1.4.1.tar.xz"
build_package "isl" "https://libisl.sourceforge.io/isl-0.28.tar.xz"
build_package "attr" "https://download.savannah.gnu.org/releases/attr/attr-2.6.0.tar.gz"
build_package "acl" "https://download.savannah.gnu.org/releases/acl/acl-2.4.0.tar.xz"
build_package "libcap" "https://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-2.78.tar.xz"
build_package "libxcrypt" "https://github.com/besser82/libxcrypt/releases/download/v4.5.2/libxcrypt-4.5.2.tar.xz"
build_package "shadow" "https://github.com/shadow-maint/shadow/releases/download/4.20.2/shadow-4.20.2.tar.xz"
build_package "gawk" "https://ftpmirror.gnu.org/gawk/gawk-5.4.1.tar.xz"
build_package "gcc" "https://ftpmirror.gnu.org/gcc/gcc-16.2.0/gcc-16.2.0.tar.xz"
build_package "ncurses" "https://invisible-mirror.net/archives/ncurses/ncurses-6.6.tar.gz"
build_package "sed" "https://ftpmirror.gnu.org/sed/sed-4.10.tar.xz"
build_package "psmisc" "https://sourceforge.net/projects/psmisc/files/psmisc/psmisc-23.7.tar.xz"
build_package "gettext" "https://ftpmirror.gnu.org/gettext/gettext-1.0.tar.xz"
build_package "bison" "https://ftpmirror.gnu.org/bison/bison-3.8.2.tar.xz"
build_package "grep" "https://ftpmirror.gnu.org/grep/grep-3.12.tar.xz"
build_package "bash" "https://ftpmirror.gnu.org/bash/bash-5.3.tar.gz"
build_package "libtool" "https://ftpmirror.gnu.org/libtool/libtool-2.6.2.tar.xz"
build_package "gdbm" "https://ftpmirror.gnu.org/gdbm/gdbm-1.26.tar.gz"
build_package "gperf" "https://ftpmirror.gnu.org/gperf/gperf-3.3.tar.gz"
build_package "expat" "https://github.com/libexpat/libexpat/releases/download/R_2_8_3/expat-2.8.3.tar.xz"
build_package "inetutils" "https://ftpmirror.gnu.org/inetutils/inetutils-2.8.tar.gz"
build_package "less" "https://www.greenwoodsoftware.com/less/less-704.tar.gz"
build_package "perl" "https://www.cpan.org/src/5.0/perl-5.44.0.tar.xz"
build_package "autoconf" "https://ftpmirror.gnu.org/autoconf/autoconf-2.73.tar.xz"
build_package "automake" "https://ftpmirror.gnu.org/automake/automake-1.18.1.tar.xz"
build_package "openssl" "https://github.com/openssl/openssl/releases/download/openssl-4.0.1/openssl-4.0.1.tar.gz"
build_package "libelf" "https://sourceware.org/ftp/elfutils/0.195/elfutils-0.195.tar.bz2"
build_package "libffi" "https://github.com/libffi/libffi/releases/download/v3.8.0/libffi-3.8.0.tar.gz"
build_package "sqlite" "https://sqlite.org/2026/sqlite-autoconf-3530400.tar.gz" "https://sqlite.org/2026/sqlite-doc-3530400.zip"
build_package "mpdecimal" "https://www.bytereef.org/software/mpdecimal/releases/mpdecimal-4.0.1.tar.gz"
build_package "python" "https://www.python.org/ftp/python/3.14.7/Python-3.14.7.tar.xz" "https://www.linuxfromscratch.org/patches/downloads/Python/Python-3.14.7-openssl_4-1.patch"
build_package "flitcore" "https://pypi.org/packages/source/f/flit-core/flit_core-4.0.2.tar.gz"
build_package "packaging" "https://files.pythonhosted.org/packages/source/p/packaging/packaging-26.3.tar.gz"
build_package "wheel" "https://pypi.org/packages/source/w/wheel/wheel-0.48.0.tar.gz"
build_package "setuptools" "https://pypi.org/packages/source/s/setuptools/setuptools-84.0.0.tar.gz"
build_package "meson" "https://github.com/mesonbuild/meson/releases/download/1.12.0/meson-1.12.0.tar.gz"
build_package "kmod" "https://www.kernel.org/pub/linux/utils/kernel/kmod/kmod-34.2.tar.xz"
build_package "coreutils" "https://ftpmirror.gnu.org/coreutils/coreutils-9.11.tar.xz"
build_package "diffutils" "https://ftpmirror.gnu.org/diffutils/diffutils-3.12.tar.xz"
build_package "findutils" "https://ftpmirror.gnu.org/findutils/findutils-4.11.0.tar.xz"
build_package "groff" "https://ftpmirror.gnu.org/groff/groff-1.24.1.tar.gz"
build_package "grub" "https://ftpmirror.gnu.org/grub/grub-2.14.tar.xz"
build_package "gzip" "https://ftpmirror.gnu.org/gzip/gzip-1.14.tar.xz"
build_package "iproute2" "https://www.kernel.org/pub/linux/utils/net/iproute2/iproute2-7.1.0.tar.xz"
build_package "kbd" "https://www.kernel.org/pub/linux/utils/kbd/kbd-2.10.0.tar.xz" "https://www.linuxfromscratch.org/patches/downloads/kbd/kbd-2.10.0-backspace-1.patch"
build_package "libpipeline" "https://download.savannah.gnu.org/releases/libpipeline/libpipeline-1.5.8.tar.gz"
build_package "make" "https://ftpmirror.gnu.org/make/make-4.4.1.tar.gz"
build_package "patch" "https://ftpmirror.gnu.org/patch/patch-2.8.tar.xz"
build_package "tar" "https://ftpmirror.gnu.org/tar/tar-1.35.tar.xz" "https://www.linuxfromscratch.org/patches/downloads/tar/tar-1.35-acl_fix-1.patch"
build_package "texinfo" "https://ftpmirror.gnu.org/texinfo/texinfo-7.3.tar.xz"
build_package "vim" "https://github.com/vim/vim/archive/v9.2.1025/vim-9.2.1025.tar.gz"
build_package "markupsafe" "https://pypi.org/packages/source/M/MarkupSafe/markupsafe-3.0.3.tar.gz"
build_package "jinja2" "https://pypi.org/packages/source/J/Jinja2/jinja2-3.1.6.tar.gz"
build_package "systemd" "https://github.com/systemd/systemd/archive/v261.2/systemd-261.2.tar.gz" "https://anduin.linuxfromscratch.org/LFS/systemd-man-pages-261.2.tar.xz"
build_package "dbus" "https://dbus.freedesktop.org/releases/dbus/dbus-1.16.2.tar.xz"
build_package "mandb" "https://download.savannah.gnu.org/releases/man-db/man-db-2.13.1.tar.xz"
build_package "procpsng" "https://sourceforge.net/projects/procps-ng/files/Production/procps-ng-4.0.7.tar.xz"
build_package "utillinux" "https://www.kernel.org/pub/linux/utils/util-linux/v2.42/util-linux-2.42.2.tar.xz"
build_package "e2fsprogs" "https://downloads.sourceforge.net/project/e2fsprogs/e2fsprogs/v1.47.4/e2fsprogs-1.47.4.tar.gz"
build_package "cleanup" ""
build_package "initconfig" ""
build_package "kernel" "https://www.kernel.org/pub/linux/kernel/v7.x/linux-7.1.8.tar.xz"
build_package "post_core" ""
build_package_nontar "nvidia_driver" "https://us.download.nvidia.com/XFree86/Linux-x86_64/610.57.04/NVIDIA-Linux-x86_64-610.57.04.run"

build_package "bashstartup" ""

build_package "icu" "https://github.com/unicode-org/icu/releases/download/release-78.3/icu4c-78.3-sources.tgz"
build_package "libxml2" "https://download.gnome.org/sources/libxml2/2.15/libxml2-2.15.3.tar.xz"
build_package "nghttp2" "https://github.com/nghttp2/nghttp2/releases/download/v1.70.0/nghttp2-1.70.0.tar.xz"
build_package "libtasn1" "https://mirrors.ibiblio.org/gnu/libtasn1/libtasn1-4.21.0.tar.gz"
build_package "nspr" "https://archive.mozilla.org/pub/nspr/releases/v4.40/src/nspr-4.40.tar.gz"
build_package "nss" "https://archive.mozilla.org/pub/security/nss/releases/NSS_3_126_RTM/src/nss-3.126.tar.gz" "https://www.linuxfromscratch.org/glfs/view/13.1/download/nss/nss-standalone-1.patch"
build_package "p11kit" "https://github.com/p11-glue/p11-kit/releases/download/0.26.5/p11-kit-0.26.5.tar.xz"
build_package "makeca" "https://github.com/lfs-book/make-ca/archive/v1.16.1/make-ca-1.16.1.tar.gz"
build_package "libunistring" "https://mirrors.ibiblio.org/gnu/libunistring/libunistring-1.4.2.tar.xz"
build_package "libidn2" "https://mirrors.ibiblio.org/gnu/libidn/libidn2-2.3.8.tar.gz"
build_package "libidn2" "https://mirrors.ibiblio.org/gnu/libidn/libidn2-2.3.8.tar.gz"
build_package "libpsl" "https://github.com/rockdaboot/libpsl/releases/download/0.23.3/libpsl-0.23.3.tar.gz"
build_package "curl" "https://curl.se/download/curl-8.21.0.tar.xz"
build_package "wget" "https://mirrors.ibiblio.org/gnu/wget/wget-1.25.0.tar.gz"

build_package "pam" "https://github.com/linux-pam/linux-pam/releases/download/v1.7.2/Linux-PAM-1.7.2.tar.xz" "https://anduin.linuxfromscratch.org/BLFS/Linux-PAM/Linux-PAM-1.7.2-docs.tar.xz"

build_package "shadowpam" "https://github.com/shadow-maint/shadow/releases/download/4.20.2/shadow-4.20.2.tar.xz"
build_package "systemdpam" "https://github.com/systemd/systemd/archive/v261.2/systemd-261.2.tar.gz"

build_package "duktape" "https://duktape.org/duktape-2.7.0.tar.xz"
build_package "glib" "https://download.gnome.org/sources/glib/2.88/glib-2.88.3.tar.xz" "https://download.gnome.org/sources/gobject-introspection/1.86/gobject-introspection-1.86.0.tar.xz" "https://www.linuxfromscratch.org/glfs/view/13.1/download/glib/glib-skip_warnings-1.patch"
build_package "shared_mime_info" "https://gitlab.freedesktop.org/xdg/shared-mime-info/-/archive/2.5.1/shared-mime-info-2.5.1.tar.gz"
build_package "desktop_file_utils" "https://www.freedesktop.org/software/desktop-file-utils/releases/desktop-file-utils-0.28.tar.xz"
build_package "polkit" "https://github.com/polkit-org/polkit/archive/127/polkit-127.tar.gz"

echo "DONE"
