name = "grub"
version = "2.14"
source = "https://ftpmirror.gnu.org/grub/grub-2.14.tar.xz"
deps = [
    "groff 1.23.0"
]
extras = [
    
]
runtime_deps = [
    "glibc 2.43",
    "bash 5.3",
    "gettext 1.0",
    "xz 5.8.2",
    "sed 4.9"
]