name = "gst-plugins-bad"
version = "1.28.0"
source = "https://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-1.28.0.tar.xz"
deps = [
    "gst-plugins-base 1.28.0",
    "libaom 3.13.1",
    "libdvdnav 7.0.0",
    "svt-av1 4.0.1",
    "soundtouch 2.4.0"
]
extras = [
    "https://www.linuxfromscratch.org/patches/blfs/svn/gst-plugins-bad-1.28.0-zxing_cpp_3-1.patch"
]