name = "gdbm"
version = "1.26"
source = "https://ftpmirror.gnu.org/gdbm/gdbm-1.26.tar.gz"
deps = [
    "libtool 2.5.4"
]
extras = [
    
]
runtime_deps = [
    "glibc 2.43",
    "bash 5.3",
    "readline 8.3"
]