name = "psmisc"
version = "23.7"
source = "https://sourceforge.net/projects/psmisc/files/psmisc/psmisc-23.7.tar.xz"
deps = [
    "sed 4.9"
]
extras = [
    
]
runtime_deps = [
    "glibc 2.43",
    "ncurses 6.6"
]
