name = "glibc"
version = "2.43"
source = "https://ftpmirror.gnu.org/glibc/glibc-2.43.tar.xz"
deps = [
    "man-pages 6.17",
    "iana-etc 20260202"
]
extras = [
    "https://www.linuxfromscratch.org/patches/lfs/development/glibc-fhs-1.patch",
    "https://www.iana.org/time-zones/repository/releases/tzdata2025c.tar.gz"
]
