name = "inetutils"
version = "2.7"
source = "https://ftpmirror.gnu.org/inetutils/inetutils-2.7.tar.gz"
deps = [
    "expat 2.7.4"
]
extras = [
    
]
runtime_deps = [
    "glibc 2.43",
    "ncurses 6.6",
    "readline 8.3"
]
