name = "autoconf"
version = "2.72"
source = "https://ftpmirror.gnu.org/autoconf/autoconf-2.72.tar.xz"
deps = [
    "intltool 0.51.0"
]
extras = [
    
]
runtime_deps = [
    "glibc 2.43",
    "bash 5.3",
    "coreutils 9.10",
    "grep 3.12",
    "m4 1.4.21",
    "make 4.4.1",
    "sed 4.9",
    "texinfo 7.2"
]