name = "qtwebengine"
version = "6.10.2"
source = "https://download.qt.io/official_releases/qt/6.10/6.10.2/submodules/qtwebengine-everywhere-src-6.10.2.tar.xz"
deps = [
    "cups 2.4.16",
    "html5lib 1.1",
    "nodejs 22.22.0",
    "pciutils 3.14.0",
    "qt 6.10.2",
    "ffmpeg 8.0.1",
    "libevent 2.1.12",
    "libwebp 1.6.0",
    "libxslt 1.1.45",
    "pipewire 1.6.0"
]
extras = [
    
]