#!/usr/bin/env python3

import sys
import os
import re
from pathlib import Path

DEFAULT_PATH = "/usr/share/pullinux/packages"
BASE_DIR = Path(os.environ.get("PLX_PCK_PATH", DEFAULT_PATH)).expanduser()

def get_latest_version(pkg_name):
    first_char = pkg_name[0].lower()
    pkg_root = BASE_DIR / first_char

    pattern = f"{pkg_name}-*"
    matches = list(pkg_root.glob(pattern))

    if not matches:
        print(f"NOT FOUND: {pkg_name}")
        exit(1)

    versions = [m.name.replace(f"{pkg_name}-", "") for m in matches]
    versions.sort(key=lambda s: [int(u) for u in re.findall(r'\d+', s)])
    return versions[-1]


name = sys.argv[1]
version = get_latest_version(name)

print(f"Package exists: {name} {version}")
