#!/usr/bin/env python3

import os
import re
import shutil
import datetime
import subprocess
import tomllib
from pathlib import Path

PLX = Path("/")
PCK_PATH = Path(os.environ.get("PLX_PCK_PATH", "/usr/share/pullinux/packages"))
BIN_DIR = PCK_PATH / "bin"

# Location of installed manifests
PLX_VAR_LIB = PLX / "var/lib/pullinux/packages"

BUILD_SCRIPT_PATH = Path("/usr/bin")

# Local build means that it won't install in a chroot environment.
local_build = True

def get_latest_version(pkg_name):
    # Finds the highest version number available in the package recipes.
    first_char = pkg_name[0].lower()
    pkg_root = PCK_PATH / first_char
    if not pkg_root.exists():
        print(f"No version {pkg_root}")
        return None
    
    pattern = f"{pkg_name}-*"
    matches = list(pkg_root.glob(pattern))
    if not matches:
        print(f"No version matches {pkg_root}")
        return None
    
    # Natural sort for versions (e.g., 2.11 > 2.2)
    versions = [m.name.replace(f"{pkg_name}-", "") for m in matches]
    versions.sort(key=lambda s: [int(u) if u.isdigit() else u for u in re.split(r'(\d+)', s)])
    return versions[-1]

def is_installed(name, version):
    # Checks the Pullinux DB to see if this specific version is already there.
    mf_entry = PLX_VAR_LIB / f"{name}-{version}.toml"
    return mf_entry.exists()

def get_manifest(txz_path):
    # Returns a list of all files and directories in the package archive.
    res = subprocess.run(["tar", "-tf", str(txz_path)], capture_output=True, text=True)

    if res.returncode == 0:
        return [line.strip().lstrip('./') for line in res.stdout.split('\n') if line.strip()]

    return []

def record_install(name, version, recipe_path, txz_path):
    # Writes a version-specific receipt including a file manifest for uninstallation (TBD).
    PLX_VAR_LIB.mkdir(parents=True, exist_ok=True)
    mf_entry = PLX_VAR_LIB / f"{name}-{version}.toml"
    
    manifest = get_manifest(txz_path)

    # Format the manifest as a pretty-printed TOML array
    manifest_str = "[\n" + ",\n".join([f'    "{f}"' for f in manifest]) + ",\n]"
    
    content = (
        f'name = "{name}"\n'
        f'version = "{version}"\n'
        f'install_date = "{datetime.datetime.now().isoformat()}"\n'
        f'recipe_source = "{recipe_path}"\n'
        f'manifest = {manifest_str}\n'
    )

    mf_entry.write_text(content)

    print(f"INST:> Recorded install manifest: {mf_entry}")

def install_package(name, version=None, auto_yes=False, dest=None, runtime=None):
    if not version:
        version = get_latest_version(name)
        if not version:
            print(f"INST:> ERROR: Recipe for '{name}' not found.")
            exit(1)

    if is_installed(name, version):
        return

    recipe_dir = PCK_PATH / name[0].lower() / f"{name}-{version}"
    recipe_file = recipe_dir / "pck.toml"
    
    if not recipe_file.exists():
        print(f"INST:> ERROR: pck.toml missing for {name}-{version}")
        exit(1)

    with open(recipe_file, "rb") as f:
        #print(f"Loading recipe file {recipe_file}")
        recipe_data = tomllib.load(f)

    deps = recipe_data.get("deps", [])

    if runtime:
        deps = recipe_data.get("runtime_deps", [])

        if len(deps) == 0 and name != "base-structure":
            print(f"INST:> ERROR: No Runtime Dependencies for {name}!\n")
            exit(1)

    if deps:
        print(f"INST:> Resolving dependencies for {name}-{version}...")

        for dep_str in deps:
            dep_parts = dep_str.split()
            if len(dep_parts) == 2:
                d_name, d_ver = dep_parts
                #print(f"INSTPCK: {d_name} - {d_ver}")
                install_package(d_name, d_ver, auto_yes, dest, runtime)
            else:
                print(f"INST:> ERROR: Invalid dependency format '{dep_str}' in {name} recipe.")
                exit(1)

    txz_name = f"{name}-{version}-plx-3.0.txz"
    txz_path = BIN_DIR / txz_name

    if not txz_path.exists():
        print(f"INST:> Binary {txz_name} not found.")

        if runtime:
            print(f"INST:> Cannot install runtime {name} without binary. Aborting.")
            exit(1)

        choice = 'y' if auto_yes else input(f"    Would you like to build {name}-{version} now? (y/N): ").lower()
        
        if choice == 'y':
            print(f"INST:> Executing plx-build {name} {version}...")

            if dest:
                build_res = subprocess.run([str(BUILD_SCRIPT_PATH / "plx-build"), name, "-v", version, "--dest", dest])
            else:
                build_res = subprocess.run([str(BUILD_SCRIPT_PATH / "plx-build"), name, "-v", version])

            if build_res.returncode != 0:
                print(f"INST:> ERROR: Build failed for {name}. Aborting installation.")
                exit(1)
        else:
            print(f"INST:> Cannot install {name} without binary. Aborting.")
            exit(1)

    plx_tmp = PLX / "tmp"
    plx_tmp.mkdir(parents=True, exist_ok=True)
    staged_txz = plx_tmp / txz_name
    
    print(f"INST:> Staging {txz_name} for internal extraction to {staged_txz}...")
    shutil.copy2(txz_path, staged_txz)

    print(f"INST:> Extracting {name}-{version} ...")

    extract_script = f"tar -xhf /tmp/{txz_name} -C /"

    tar_extract_command = [
            "chroot", str(PLX), "/usr/bin/env", "-i",
            "HOME=/root", "TERM=xterm",
            "/bin/bash", "-c", extract_script
        ]

    if local_build:
        tar_extract_command = [
            "/bin/bash", "--login", "-c", extract_script
        ]
    else:
        print(f"INST:> Extracting in chroot {PLX}")

    # Before extracting, see if a left over installer is there, dont' want to run that...
    install_script_abs = PLX / ".install/install.sh"
    if install_script_abs.exists():
        print(f"INST:> Cleaning up previous installer...")
        os.remove(install_script_abs)

    if name == "base-structure":
        print("INST:> Setting up base structure...")

        tar_extract_command = [
            "/bin/bash", "-c", f"tar -xf {PLX}/tmp/{txz_name} -C {PLX}", 
        ]

    try:
        subprocess.run(tar_extract_command, check=True)
    except subprocess.CalledProcessError:
        print(f"INST:> ERROR: Extraction install failed.")
        if staged_txz.exists(): os.remove(staged_txz)
        exit(1)
    finally:
        if staged_txz.exists():
            os.remove(staged_txz)

    # Run Post-Install Script (.install/install.sh)
    install_script_abs = PLX / ".install/install.sh"
    if install_script_abs.exists():
        print(f"INST:> Running post-install for {name}...")
        
        installer_cmd = [
            "chroot", str(PLX), "/usr/bin/env", "-i",
            "HOME=/root", "TERM=xterm",
            "/bin/bash", "--login", "-e", "-c", "cd /.install && bash -e /.install/install.sh"
        ]
        
        if local_build:
            print("INST:> Running install locally")

            installer_cmd = [
                "/bin/bash", "--login", "-e", "-c", "cd /.install && bash -e /.install/install.sh"
            ]

        try:
            subprocess.run(installer_cmd, check=True)
        except subprocess.CalledProcessError:
            print(f"INST:> ERROR: Post-install script returned an error.")
            print("INST:> INSTALL FAILED")
            exit(1)
        
        # Cleanup installer data
        shutil.rmtree(PLX / ".install", ignore_errors=True)

    # Run /sbin/ldconfig after install, some packages need this done, so just do for all...    
    try:
        ldconfig_cmd = [
            "chroot", str(PLX), "/usr/bin/env", "-i",
            "HOME=/root", "TERM=xterm",
            "/bin/bash", "-e", "-c", "ldconfig"
        ]

        if local_build:
            ldconfig_cmd = [
                "/sbin/ldconfig"
            ]

        subprocess.run(ldconfig_cmd, check=True)
    except subprocess.CalledProcessError:
        print(f"INST:> ERROR: ldconfig run error...")
        exit(1)
    
    # Write manifest install record
    record_install(name, version, str(recipe_dir), txz_path)
    print(f"INST:> INSTALLED {name}-{version} Successfully.")

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Pullinux Package Installer")
    parser.add_argument("name", help="Package name")
    parser.add_argument("-v", "--version", help="Specific version")
    parser.add_argument("-y", "--yes", action="store_true", help="Auto-build if binary is missing")
    parser.add_argument("-r", "--runtime", action="store_true", help="Use runtime dependencies only")
    parser.add_argument("-d", "--dest", help="Destination of where to build in a chroot environment")

    args = parser.parse_args()
    
    if args.dest:
        local_build = False
        PLX = Path(args.dest)
        PLX_VAR_LIB = PLX / "var/lib/pullinux/packages"
        BUILD_SCRIPT_PATH = Path("./")

        if not PLX_VAR_LIB.exists():
            print("INST:> Installing Base Structure First...")
            install_package("base-structure", "3.0", args.yes, args.dest, args.runtime)
        else:
            print(f"Structure exists: {PLX_VAR_LIB}")

        if not (PLX / "dev/tty").exists():
            print(f"First you must mount virtual environment in {PLX}")
            exit(1)

    try:
        install_package(args.name, args.version, args.yes, args.dest, args.runtime)
    except KeyboardInterrupt:
        print("\nINST:> Installation interrupted by user.")
        exit(1)
