#!/usr/bin/env python3
import os
import tomllib
from pathlib import Path

PLX = Path("/")
PLX_VAR_LIB = PLX / "var/lib/pullinux/packages"

# Local build means that it won't install in a chroot environment.
local_build = True

def is_dir_empty(path):
    with os.scandir(path) as it:
        return not any(it) # Returns right away if something found...

def uninstall_package(name, version):
    db_entry = PLX_VAR_LIB / f"{name}-{version}.toml"
    
    if not db_entry.exists():
        print(f"UNINSTALL:> ERROR: No manifest found for {name}-{version}. Is it installed?")
        exit(1)

    print(f"UNINSTALL:> Reading manifest for {name}-{version}...")
    with open(db_entry, "rb") as f:
        data = tomllib.load(f)
        manifest = data.get("manifest", [])

    # We need to separate files and directories. 
    # We delete files first, then attempt to remove directories in reverse order.
    files_to_remove = []
    dirs_to_check = []

    for item in manifest:
        if not item: continue # Skip empty entries
        
        full_path = PLX / item

        if full_path.is_dir():
            dirs_to_check.append(full_path)
        else:
            files_to_remove.append(full_path)

    print(f"UNINSTALL:> Removing files...")
    for f in files_to_remove:
        if f.exists() or f.is_symlink():
            try:
                print(f"    - RM: {f}")
                f.unlink()
            except Exception as e:
                print(f"UNINSTALL:> ERROR: Failed to remove {f}: {e}")

    print(f"UNINSTALL:> Cleaning up directories...")
    dirs_to_check.sort(key=lambda x: len(str(x)), reverse=True)
    
    for d in dirs_to_check:
        if d.exists() and d.is_dir() and is_dir_empty(d):
            try:
                if d.is_symlink():
                    print(f"UNINSTALL:>     - Unlink Dir: {d}")
                    d.unlink()
                else:
                    print(f"UNINSTALL:>     - RMDIR: {d}")
                    os.rmdir(d)
            except OSError:
                pass

    db_entry.unlink()
    print(f"UNINSTALL:> {name}-{version} uninstalled successfully.")

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Pullinux Package Uninstaller")
    parser.add_argument("name", help="Package name")
    parser.add_argument("version", help="Package version")
    parser.add_argument("-d", "--dest", help="Destination of where to build in a chroot environment")

    args = parser.parse_args()

    if args.dest:
        local_build = False
        PLX = Path(args.dest)
        PLX_VAR_LIB = PLX / "var/lib/pullinux/packages"

        if not (PLX / "dev/tty").exists():
            print(f"UNINSTALL:> ERROR: First you must mount virtual environment in {PLX}")
            exit(1)

    uninstall_package(args.name, args.version)
