name = "vim"
version = "9.2.0000"
source = "https://github.com/vim/vim/archive/v9.2.0000/vim-9.2.0000.tar.gz"
deps = [
    "texinfo 7.2"
]
extras = [
    
]
runtime_deps = [
    "acl 2.3.2",
    "attr 2.5.2",
    "glibc 2.43",
    "python 3.14.3",
    "ncurses 6.6",
    "tcl 8.6.17"
]
