name = "mpc"
version = "1.3.1"
source = "https://ftpmirror.gnu.org/mpc/mpc-1.3.1.tar.gz"
deps = [
    "mpfr 4.2.2"
]
extras = [
    
]
runtime_deps = [
    "glibc 2.43",
    "gmp 6.3.0",
    "mpfr 4.2.2"
]
