name = "khelpcenter"
version = "25.08.3"
source = "https://download.kde.org/stable/release-service/25.08.3/src/khelpcenter-25.08.3.tar.xz"
deps = [
    "kde-framework 6.23.0",
    "xapian 1.4.30",
    "qtwebengine 6.10.2"
]
extras = [
    
]