name = "gst-plugins-bad"
version = "1.28.1"
source = "https://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-1.28.1.tar.xz"
deps = [
    "gst-plugins-base 1.28.1",
    "libaom 3.13.3",
    "libdvdnav 7.0.0",
    "svt-av1 4.0.1",
    "soundtouch 2.4.0"
]
extras = [
    
]