name = "html5lib"
version = "1.1"
source = "https://files.pythonhosted.org/packages/source/h/html5lib/html5lib-1.1.tar.gz"
deps = [
    "six 1.17.0",
    "webencodings 0.5.1"
]
extras = [
    "https://www.linuxfromscratch.org/patches/blfs/svn/html5lib-1.1-python_3.14_buildfix-1.patch"
]