name = "wayland"
version = "1.24.0"
source = "https://gitlab.freedesktop.org/wayland/wayland/-/releases/1.24.0/downloads/wayland-1.24.0.tar.xz"
deps = [
    "libxml2 2.15.1",
    "base-dev 3.0"
]
extras = [
    
]
runtime_deps = [
    "base-system 3.0"
]
