name = "xml-parser"
version = "2.47"
source = "https://cpan.metacpan.org/authors/id/T/TO/TODDR/XML-Parser-2.47.tar.gz"
deps = [
    "perl 5.42.0"
]
extras = [
    
]
runtime_deps = [
    "perl mime-base32-1.303",
    "glibc 2.43",
    "expat 2.7.4"
]
