name = "automake"
version = "1.18.1"
source = "https://ftpmirror.gnu.org/automake/automake-1.18.1.tar.xz"
deps = [
    "autoconf 2.72"
]
extras = [
    
]
runtime_deps = [
    "glibc 2.43",
    "bash 5.3",
    "coreutils 9.10",
    "grep 3.12",
    "m4 1.4.21",
    "sed 4.9",
    "texinfo 7.2"
]