name = "perl-mime-base32"
version = "1.303"
source = "https://cpan.metacpan.org/authors/id/R/RE/REHSACK/MIME-Base32-1.303.tar.gz"
deps = [
    "base-dev 3.0"
]
extras = [
    
]
runtime_deps = [
    "gdbm 1.26",
    "glibc 2.43",
    "libxcrypt 4.5.2"
]
