name = "tar"
version = "1.35"
source = "https://ftpmirror.gnu.org/tar/tar-1.35.tar.xz"
deps = [
    "patch 2.8"
]
extras = [
    
]
runtime_deps = [
    "acl 2.3.2",
    "attr 2.5.2",
    "bzip2 1.0.8",
    "glibc 2.43",
    "gzip 1.14",
    "xz 5.8.2"
]
