name = "base-config"
version = "3.0"
source = "none"
deps = [
    "linux-kernel 6.18.10"
]
extras = [
    
]
runtime_deps = [
    "linux-kernel 6.18.10",
    "bash 5.3",
    "libcap 2.77",
    "shadow 4.19.3",
    "ncurses 6.6",
    "sed 4.9",
    "psmisc 23.7",
    "grep 3.12",
    "inetutils 2.7",
    "less 692",
    "perl mime-base32-1.303",
    "openssl 3.6.1",
    "libelf 0.194",
    "libffi 3.5.2",
    "python 3.14.3",
    "sqlite 3510200",
    "kmod 34.2",
    "coreutils 9.10",
    "diffutils 3.12",
    "gawk 5.3.2",
    "findutils 4.10.0",
    "grub 2.14",
    "gzip 1.14",
    "iproute2 6.18.0",
    "kbd 2.9.0",
    "libpipeline 1.5.8",
    "tar 1.35",
    "vim 9.2.0000",
    "systemd 259.1",
    "dbus 1.16.2",
    "man-db 2.13.1",
    "procps-ng 4.0.6",
    "util-linux 2.41.3",
    "e2fsprogs 1.47.3"
]
