name = "steam"
version = "1.0.0.85"
source = "https://repo.steampowered.com/steam/archive/precise/steam_1.0.0.85.tar.gz"
deps = [
    "base-xorg 3.0",
    "xdg-user-dirs 0.19",
    "libgpg-error 1.59"
]
extras = [
    
]