name = "bc"
version = "7.0.3"
source = "https://github.com/gavinhoward/bc/releases/download/7.0.3/bc-7.0.3.tar.xz"
deps = [
    "m4 1.4.21"
]
extras = [
    
]
runtime_deps = [
    "glibc 2.43",
    "ncurses 6.6",
    "readline 8.3"
]