name = "libpipeline"
version = "1.5.8"
source = "https://download.savannah.gnu.org/releases/libpipeline/libpipeline-1.5.8.tar.gz"
deps = [
    "kbd 2.9.0"
]
extras = [
    
]
runtime_deps = [
    "glibc 2.43"
]
