name = "sed"
version = "4.9"
source = "https://ftpmirror.gnu.org/sed/sed-4.9.tar.xz"
deps = [
    "ncurses 6.6"
]
extras = [
    
]
runtime_deps = [
    "acl 2.3.2",
    "attr 2.5.2",
    "glibc 2.43"
]
